web:
  port: '{$PORT}'
  maxHeaderSize: 512000 #500KB
  maxContentSize: 2097152 #2MB
  customError:
    notFound: /error/404
    serverError: /error/500
persistent:
  dataSource:
    host: '{$DB_HOST}'
    db: '{$DB_NAME}'
    user: '{$DB_USER}'
    password: '{$DB_PASSWORD}'
    port: 3306
  option:
    schema:
      actions:
        - migrate
        - validate
    test: true