---
- name: Add nginx latest repo
  lineinfile:
    dest: /etc/apt/sources.list
    state: present
    line: '{{item}} http://nginx.org/packages/debian/ stretch nginx'
    insertafter: EOF
  with_items:
    - deb
    - deb-src
- name: Install nginx
  apt:
    name: nginx={{ nginx_version }}
    update_cache: true
- name: Copy Nginx app conf file
  template:
    src: templates/{{ item.key }}
    dest: /etc/nginx/{{ item.value }}
    force: true
    owner: '{{ nginx_user }}'
    mode: 0755
  with_dict:
    nginx.conf.j2: nginx.conf
    app_server.conf.j2: conf.d/app_server.conf
#==================================================
# for maintenance
#==================================================
- name: Chown /var/www/html
  file:
    path: /var/www/html
    state: directory
    group: '{{ app_group }}'
    mode: 0775
- name: Copy Nginx maintenance html
  template:
    src: templates/{{ item.key }}
    dest: /var/www/html/{{ item.value }}
    force: true
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    mode: 0755
  with_dict:
    maintenance.html: _maintenance.html
- name: Validate Nginx conf file
  command: nginx -t -c /etc/nginx/nginx.conf
- name: Restart Nginx service
  command: service nginx restart
